version: "3"
services:
  websocket_app:
    build: .
    container_name: websocket_app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: sh -c "node ./src/app.js & npm run test"

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
